import { createRequestHandler, ServerBuild } from "@remix-run/cloudflare";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server";

const handler = createRequestHandler(build as unknown as ServerBuild);

const fetch = async (request: Request, env: Env, ctx: ExecutionContext) => {
  const context = {
    request,
    context: {
      cloudflare: {
        env,
        ctx: {
          waitUntil: ctx.waitUntil.bind(ctx) ?? (() => {}),
          passThroughOnException:
            ctx.passThroughOnException.bind(ctx) ?? (() => {}),
        },
        cf: request.cf as never,
        caches: caches as never,
      },
    },
  };
  return handler(request, context.context as never);
};

export default {
  fetch,
};
